name: 发布流程
on:
  push:
    branches:
      - build-test
    tags:
      - "v*"

jobs:
  # Build sources for every OS
  github_build:
    name: 构建发布二进制
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: changqiao-terminal-linux-amd64.tar.gz
            arch: x86_64

          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: changqiao-terminal-linux-arm64.tar.gz
            arch: aarch64

          - target: x86_64-apple-darwin
            os: macOS-latest
            name: changqiao-terminal-darwin-amd64.tar.gz
            arch: x86_64

          - target: aarch64-apple-darwin
            os: macOS-latest
            name: changqiao-terminal-darwin-arm64.tar.gz
            arch: aarch64

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: changqiao-terminal-windows-amd64.zip
            arch: x86_64

          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            name: changqiao-terminal-linux-musl-amd64.tar.gz
            arch: x86_64

          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            name: changqiao-terminal-linux-musl-arm64.tar.gz
            arch: aarch64

    runs-on: ${{ matrix.os }}
    steps:
      - name: 准备 | 检出代码
        uses: actions/checkout@v4

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(?<version>.*)"

      # Cache files between builds
      - name: 准备 | 缓存 Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: 安装 Musl 工具
        if: matrix.target == 'x86_64-unknown-linux-musl' || matrix.target == 'aarch64-unknown-linux-musl'
        run: |
          sudo apt-get install musl-tools

      - name: 准备 | Rust 工具链
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}

      - name: 构建 | 编译
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path Cargo.toml --release --target ${{ matrix.target }} --config 'package.version="${{ steps.tagName.outputs.version }}"'
          use-cross: ${{ matrix.os == 'ubuntu-latest' }}

      - name: 整理产物 [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip changqiao.exe
          7z a ../../../${{ matrix.name }} changqiao.exe
          cd -

      - name: 整理产物 [Linux & macOS]
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          # TODO: investigate better cross platform stripping
          strip changqiao || true
          tar czvf ../../../${{ matrix.name }} changqiao
          cd -

      - name: 验证二进制 [Linux & macOS]
        if: matrix.arch == 'x86_64' && matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          ./changqiao --version
          cd -

      - name: 验证二进制 [Windows]
        if: matrix.arch == 'x86_64' && matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          ./changqiao.exe --version
          cd -

      - name: 发布 | 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  # Create GitHub release with Rust build targets and release notes
  github_release:
    name: 创建 GitHub 发布
    needs: github_build
    runs-on: ubuntu-latest
    steps:
      - name: 准备 | 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 准备 | 下载产物
        uses: actions/download-artifact@v4
        with:
          path: release-dist

      - name: 准备 | 生成校验和
        run: |
          ls -lha release-dist
          for file in release-dist/**/*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: 发布版本
        uses: softprops/action-gh-release@v1
        with:
          files: release-dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
